YML: looking for the allure results folder 4

diff --git a/.github/workflows/test-allure.yml b/.github/workflows/test-allure.yml
--- a/.github/workflows/test-allure.yml
+++ b/.github/workflows/test-allure.yml
@@ -32,7 +32,7 @@ jobs:
       - name: Check Allure results folder
         run: |
          echo "Listing files in Allure results folder"
-         ls -la ./bin/Debug || echo "Folder not found"
+         ls -la ./bin || echo "Folder not found"
 
       - name: Check Allure results folder
         run: |
